"""ExitBinder — binds the managed exit to its live trigger (the last armed-path seam).

`TradeLifecycle` fails closed on an armed fill with no `exit_factory`. This is that
factory. At fill time it answers one question: WHICH engine trigger, under WHICH book
config, produced the position we now hold — because the managed exit is engine.py's own
management for that (trigger, cfg), driven by `ExitDriver`, and managing any other
stream would be trading a position we did not reproduce.

Resolution is by construction + refusal, never by guess:

  1. re-detect triggers over the LIVE bars with the SAME `detect_triggers` that built the
     research caches (identical code path — the caches were generated by calling it);
  2. run the REAL `simulate()` once per book config (E3/E4) over those candidates — the
     batch substrate's own construction — and keep the trades whose entry AND stop match
     the canon's to the half-tick;
  3. re-drive each match in isolation through `ExitDriver` (entry-pinning again — the
     isolated-drive == in-context-fill property is held to real bars in
     tests/test_exit_driver.py);
  4. accept ONLY if every surviving (trigger, cfg) yields the SAME action stream.

No match, disagreeing matches, or an engine error with nothing pinned -> raise. The
lifecycle catches any factory exception and flattens (C7): an armed position that cannot
be provably bound to its backtest twin is closed, never improvised on.

Sessions: NY uses the cache band 07:45-11:00 ET and the frozen substrate configs
(`exit_cfgs()`); LONDON uses the DST-correct 08:00-10:00 Europe/London window and the
same `books()` construction `london_substrate.py` ran.
"""
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import time as dtime

import pandas as pd

from src.canon.exit_driver import ExitDriver, exit_cfgs
from src.canon.exit_live import LiveExitExecutor

NY = "America/New_York"
_STREAM_KEYS = ("kind", "reason", "price", "frac", "ts")   # same signature as the executor


def _stream_sig(actions: list[dict]) -> tuple:
    return tuple(tuple(a.get(k) for k in _STREAM_KEYS) for a in actions)


def _default_detect(bars: pd.DataFrame, start: pd.Timestamp, end: pd.Timestamp):
    from src.engine.triggers import detect_triggers
    return detect_triggers(bars, start=start, end=end)


def london_cfgs(day: str) -> list:
    """The exact configs london_substrate.py simulated `day` under: 08:00-10:00
    Europe/London converted to ET (DST-correct), max 2 trades/day, both books."""
    from scripts.grade_window_cap import books
    from scripts.run_triggers_london import london_window_et
    from src.backtest.engine import load_backtest_config
    ws, we = london_window_et(day)
    cfg = load_backtest_config().model_copy(update={
        "win_start": dtime(ws.hour, ws.minute), "win_end": dtime(we.hour, we.minute),
        "max_trades_per_day": 2})
    return list(books(cfg))


@dataclass
class ExitBinder:
    """One instance per lane; `factory` is handed to TradeLifecycle as `exit_factory`."""
    broker: object
    account: str
    armed: bool = False
    session: str = "NY"                             # "NY" | "LONDON"
    bars_fn: Callable[[], pd.DataFrame] | None = None   # ingestor.bars_frame
    journal: object | None = None                   # LiveExitExecutor journal (.note)
    detect_fn: Callable = _default_detect           # injectable (tests / cached triggers)
    driver: ExitDriver = field(default_factory=ExitDriver)
    simulate_fn: Callable | None = None             # injectable; default engine simulate

    def _note(self, text: str) -> None:
        if self.journal is not None:
            try:
                self.journal.note(text)
            except Exception:
                pass

    def _band(self, day: str) -> tuple[pd.Timestamp, pd.Timestamp]:
        if self.session == "LONDON":
            from scripts.run_triggers_london import london_window_et
            return london_window_et(day)
        return (pd.Timestamp(f"{day} 07:45", tz=NY),    # the committed caches' band
                pd.Timestamp(f"{day} 11:00", tz=NY))

    def _cfgs(self, day: str) -> list:
        return london_cfgs(day) if self.session == "LONDON" else list(exit_cfgs())

    # ---- the factory (TradeLifecycle.exit_factory) --------------------------
    def factory(self, ref: str, side: str, entry: float, stop: float,
                size: int) -> LiveExitExecutor:
        if self.simulate_fn is None:
            from src.backtest.engine import simulate
            self.simulate_fn = simulate
        bars = self.bars_fn() if self.bars_fn is not None else None
        if bars is None or len(bars) == 0:
            raise LookupError("exit binding: no bars available")
        day = str(pd.Timestamp(bars["ts_event"].iloc[-1]).tz_convert(NY).date())
        start, end = self._band(day)
        direction = "long" if side == "B" else "short"
        cands = [t for t in self.detect_fn(bars, start, end) if t.direction == direction]
        if not cands:
            raise LookupError(f"exit binding: no {direction} triggers detected in "
                              f"[{start}, {end}]")
        half = self.driver.tick / 2.0
        pinned: list[tuple] = []                    # (trigger_ts, cfg, stream_sig)
        errors: list[str] = []
        for cfg in self._cfgs(day):
            try:
                trades, _v, _e = self.simulate_fn(bars, cands, cfg)
            except Exception as e:                  # noqa: BLE001 — count, decide at the end
                errors.append(f"simulate({getattr(cfg, 'name', cfg)}): {e}")
                continue
            for tr in trades:
                if (str(tr.trade_date) == day and tr.direction == direction
                        and abs(float(tr.entry) - entry) <= half
                        and abs(float(tr.stop_initial) - stop) <= half):
                    trig = next((t for t in cands if t.ts == tr.trigger_ts), None)
                    if trig is None:
                        errors.append(f"matched fill {tr.fill_ts} but trigger "
                                      f"{tr.trigger_ts} not among candidates")
                        continue
                    res = self.driver.drive(bars, trig, cfg,
                                            canon_entry=entry, canon_stop=stop)
                    if res.entry_ok:                # the isolated re-drive must pin too
                        pinned.append((trig, cfg, _stream_sig(res.actions)))
                    else:
                        errors.append(f"in-context match {tr.trigger_ts} failed the "
                                      f"isolated pin: {res.detail}")
        if not pinned:
            raise LookupError("exit binding: no (trigger, cfg) reproduces entry="
                              f"{entry} stop={stop} on {day}"
                              + (f" [{'; '.join(errors)}]" if errors else ""))
        if len({sig for _t, _c, sig in pinned}) > 1:
            raise LookupError(f"exit binding AMBIGUOUS: {len(pinned)} pins with "
                              "disagreeing action streams — refusing to pick")
        trig, cfg, _sig = pinned[0]
        self._note(f"exit bound: trigger {trig.ts} reproduces entry={entry} "
                   f"stop={stop} ({len(pinned)} unanimous pin(s))")
        return LiveExitExecutor(broker=self.broker, ref=ref, account=self.account,
                                trigger=trig, cfg=cfg, canon_entry=entry,
                                canon_stop=stop, size=int(size), armed=self.armed,
                                journal=self.journal)
