"""v0.5 DRAFT — the Information Bump wires, engine lane (Angus directive, 18 Jul).

OPT-IN ONLY: nothing imports this module by default, so the in-flight v0.4 run is
untouched. When v0.4 results are in and Angus publishes v0.5, Pat merges with two
calls in the sequential driver:

    from src.desk.briefing_v05 import upgrade_briefing, feedback_block
    briefing = upgrade_briefing(briefing, day, asof=EXAM_CUTOFF)      # W2
    briefing["yesterday_result"] = feedback_block(day, verdicts, daily)  # W1

plus the W3 constants below for the prompt/schema bump. Data dependencies (all
committed): output/analog_briefing.csv, output/base_rates.json,
output/l2_analog_routing.csv (or allyears_daily_books.csv for 2023-25).

Replay safety: pass asof=<first exam day> so base rates come from
`build_base_rates --asof` output; the analog table is walk-forward by
construction and needs no cutoff.
"""
import json
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------- W3 constants

V05_SIZE_NOTCHES = (0.0, 0.25, 0.5, 0.75, 1.0)

V05_PROMPT_ADDENDUM = """\
## v0.5 — reason in dollars, not event-probabilities

- Your briefing now includes `analog_days` (the 15 most similar historical
  mornings and what actually paid on each), `base_rates` (three-year priors for
  mornings with today's features), and `yesterday_result` (your previous
  verdict's realized dollars vs full-size vs oracle, plus rolling-20d regret).
- Justify size and stand-down in EXPECTED DOLLARS, citing analog/base-rate
  evidence. "Risk is elevated" is not a reason; "mornings like this paid the
  momentum book +$60/day and lost the rotation book -$114/day over 51 cases"
  is a reason.
- A shrunk winner is a real loss. Your rolling sizing regret is in the
  briefing; if it is persistently negative, your caution is mispriced.
- The single-day feedback is NOISY - weigh the rolling-20d line, never
  overreact to one day.
- New required field `expected_value_usd`: your point-estimate of today's
  verdict's P&L at your chosen size. It is graded for calibration (C3).
"""


# ---------------------------------------------------------------- W2: retrieval

def _bucket(x, edges, labels):
    for hi, lab in zip(edges, labels):
        if x <= hi:
            return lab
    return labels[-1]


def upgrade_briefing(briefing: dict, day: str,
                     analog_path: str = "output/analog_briefing.csv",
                     rates_path: str = "output/base_rates.json",
                     asof: str | None = None) -> dict:
    """Fill analog_days with the A1 block and attach today's base-rate slices.

    Slim by design (briefing diet): only the digest rows matching today's
    features travel, plus the topline — not the whole book.
    """
    a = pd.read_csv(analog_path)
    row = a[a.day == day]
    if not row.empty and row.iloc[0].n_analogs > 0:
        briefing["analog_days"] = json.loads(row.iloc[0].analog_block)
    rp = Path(rates_path)
    if asof:  # replay-safe digest generated by build_base_rates --asof
        cut = rp.with_name(f"base_rates_asof_{asof}.json")
        rp = cut if cut.exists() else rp
    if rp.exists():
        digest = json.loads(rp.read_text())
        v = briefing.get("regime_vector", {}) or {}
        sh = briefing.get("shock_bars", {}) or {}
        sel = {"note": digest.get("note"), "topline": digest.get("topline"),
               "asof_cutoff": digest.get("asof_cutoff")}
        dt = v.get("day_type")
        if dt in digest.get("by_day_type", {}):
            sel["today_day_type"] = {dt: digest["by_day_type"][dt]}
        red = "red_folder" if (v.get("red_folder_today") or 0) > 0 else "clear"
        sel["today_calendar"] = {red: digest["by_red_folder"].get(red)}
        pct = sh.get("pctl_20d")
        if pct is None:                     # E2 ruler not joined yet -> CSV lookup
            sr = Path("output/shock_ruler.csv")
            if sr.exists():
                m = pd.read_csv(sr).set_index("day").shock50_pctl20
                pct = float(m[day]) if day in m.index and pd.notna(m.get(day)) else None
        if pct is not None:
            b = _bucket(pct, (0.5, 0.85, 1.01),
                        ("calm(<p50)", "mid", "elevated(>p85)"))
            sel["today_shock_regime"] = {b: digest["by_shock_percentile"].get(b)}
        briefing["base_rates"] = sel
    return briefing


# ---------------------------------------------------------------- W1: feedback

def feedback_block(day: str, verdicts: pd.DataFrame, daily: pd.DataFrame,
                   window: int = 20) -> dict | str:
    """The C2 contract: yesterday's verdict billed in dollars + rolling damper.

    daily needs columns day/pl_static/pl_e3/pl_e4 (l2_analog_routing schema;
    rename E3/E4 for the allyears file). Mechanical — costs no agent turn.
    """
    d = daily.set_index("day") if "day" in daily.columns else daily
    v = verdicts[verdicts.date < day].sort_values("date")
    v = v[v.date.isin(d.index)]
    if v.empty:
        return "(no prior verdict yet)"

    def _size(x):
        return 0.0 if (x.stand_down or x.size_multiplier == 0) else float(x.size_multiplier)

    hist = []
    for _, x in v.iterrows():
        r = d.loc[x.date]
        s = _size(x)
        full = float(r.pl_static)
        oracle = max(float(r.pl_e3), float(r.pl_e4), 0.0)
        hist.append(dict(date=x.date, s=s, realized=s * full, full=full,
                         oracle=oracle))
    h = pd.DataFrame(hist)
    y = h.iloc[-1]
    tail = h.tail(window)
    return {
        "date": y.date,
        "your_size": round(y.s, 2),
        "realized_usd": round(y.realized),
        "full_size_counterfactual_usd": round(y.full),
        "oracle_usd": round(y.oracle),
        "sizing_regret_usd": round(y.realized - y.full),
        "read_regret_usd": round(y.realized - y.oracle),
        "rolling_20d": {
            "your_cumulative_sizing_regret_usd": round((tail.realized - tail.full).sum()),
            "your_cumulative_read_regret_usd": round((tail.realized - tail.oracle).sum()),
            "your_arm_expectancy_usd": round(tail.realized.mean()),
            "champion_expectancy_usd": round(tail.full.mean()),
        },
    }
