"""v0.5 DRAFT — the Information Bump wires, engine lane (Angus directive, 18 Jul).

OPT-IN ONLY: nothing imports this module by default, so the in-flight v0.4 run is
untouched. When v0.4 results are in and Angus publishes v0.5, Pat merges with two
calls in the sequential driver:

    from src.desk.briefing_v05 import upgrade_briefing, feedback_block
    briefing = upgrade_briefing(briefing, day, asof=EXAM_CUTOFF)      # W2
    briefing["yesterday_result"] = feedback_block(day, verdicts, daily)  # W1

plus the W3 constants below for the prompt/schema bump. Data dependencies (all
committed): output/analog_briefing.csv, output/base_rates.json,
output/l2_analog_routing.csv (or allyears_daily_books.csv for 2023-25).

Replay safety: pass asof=<first exam day> so base rates come from
`build_base_rates --asof` output; the analog table is walk-forward by
construction and needs no cutoff.
"""
import json
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------- W3 constants

V05_SIZE_NOTCHES = (0.0, 0.25, 0.5, 0.75, 1.0)

V05_PROMPT_ADDENDUM = """\
## v0.5 — reason in dollars, not event-probabilities

- Your briefing now includes `analog_days` (the 15 most similar historical
  mornings and what actually paid on each), `base_rates` (three-year priors for
  mornings with today's features), and `yesterday_result` (your previous
  verdict's realized dollars vs full-size vs oracle, plus rolling-20d regret).
- Justify size and stand-down in EXPECTED DOLLARS, citing analog/base-rate
  evidence. "Risk is elevated" is not a reason; "mornings like this paid the
  momentum book +$60/day and lost the rotation book -$114/day over 51 cases"
  is a reason.
- A shrunk winner is a real loss. Your rolling sizing regret is in the
  briefing; if it is persistently negative, your caution is mispriced.
- The single-day feedback is NOISY - weigh the rolling-20d line, never
  overreact to one day.
- New required field `expected_value_usd`: your point-estimate of today's
  verdict's P&L at your chosen size. It is graded for calibration (C3).
"""


# ---------------------------------------------------------------- W2: retrieval

def _bucket(x, edges, labels):
    for hi, lab in zip(edges, labels):
        if x <= hi:
            return lab
    return labels[-1]


def upgrade_briefing(briefing: dict, day: str,
                     analog_path: str = "output/analog_briefing.csv",
                     rates_path: str = "output/base_rates.json",
                     asof: str | None = None,
                     include_topline: bool = False) -> dict:
    """Fill analog_days with the A1 block and attach today's base-rate slices.

    Slim by design (briefing diet): only the digest rows matching today's
    features travel, plus the topline — not the whole book.
    """
    a = pd.read_csv(analog_path)
    row = a[a.day == day]
    if not row.empty and row.iloc[0].n_analogs > 0:
        briefing["analog_days"] = json.loads(row.iloc[0].analog_block)
    rp = Path(rates_path)
    if asof:  # replay-safe digest generated by build_base_rates --asof
        cut = rp.with_name(f"base_rates_asof_{asof}.json")
        rp = cut if cut.exists() else rp
    if rp.exists():
        digest = json.loads(rp.read_text())
        v = briefing.get("regime_vector", {}) or {}
        sh = briefing.get("shock_bars", {}) or {}
        sel = {"note": digest.get("note"), "asof_cutoff": digest.get("asof_cutoff")}
        if include_topline:                # v0.6.3: OFF — the unconditioned "47% of
            sel["topline"] = digest.get("topline")  # days FLAT / books negative" line
            # read as standing permission to hide (Rung-1 anchor-lock diagnosis)
        dt = v.get("day_type")
        if dt in digest.get("by_day_type", {}):
            sel["today_day_type"] = {dt: digest["by_day_type"][dt]}
        red = "red_folder" if (v.get("red_folder_today") or 0) > 0 else "clear"
        sel["today_calendar"] = {red: digest["by_red_folder"].get(red)}
        # v0.7: AMT auction base-rate slices — how days with today's value position and
        # inventory stretch have actually resolved (value_position swings the momentum
        # lean 15%->37%; stretched inventory 55% FLAT). The agent's edge is book choice;
        # this is the prior that most directly informs it.
        vp = v.get("value_position")
        if vp in digest.get("by_value_position", {}):
            sel["today_value_position"] = {vp: digest["by_value_position"][vp]}
        inv = v.get("inventory_pts")
        if inv is not None:
            ib = ("short>40pts" if inv < -40 else "long>40pts" if inv > 40 else "neutral")
            if ib in digest.get("by_overnight_inventory", {}):
                sel["today_inventory"] = {ib: digest["by_overnight_inventory"][ib]}
        pct = sh.get("pctl_20d")
        if pct is None:                     # E2 ruler not joined yet -> CSV lookup
            sr = Path("output/shock_ruler.csv")
            if sr.exists():
                m = pd.read_csv(sr).set_index("day").shock50_pctl20
                pct = float(m[day]) if day in m.index and pd.notna(m.get(day)) else None
        if pct is not None:
            b = _bucket(pct, (0.5, 0.85, 1.01),
                        ("calm(<p50)", "mid", "elevated(>p85)"))
            sel["today_shock_regime"] = {b: digest["by_shock_percentile"].get(b)}
        briefing["base_rates"] = sel
    return briefing


# ---------------------------------------------------------------- W1: feedback

def feedback_block(day: str, verdicts: pd.DataFrame, daily: pd.DataFrame,
                   window: int = 20) -> dict | str:
    """The C2 contract: yesterday's verdict billed in dollars + rolling damper.

    daily needs columns day/pl_static/pl_e3/pl_e4 (l2_analog_routing schema;
    rename E3/E4 for the allyears file). Mechanical — costs no agent turn.
    """
    d = daily.set_index("day") if "day" in daily.columns else daily
    v = verdicts[verdicts.date < day].sort_values("date")
    v = v[v.date.isin(d.index)]
    if v.empty:
        return "(no prior verdict yet)"

    def _size(x):
        return 0.0 if (x.stand_down or x.size_multiplier == 0) else float(x.size_multiplier)

    hist = []
    for _, x in v.iterrows():
        r = d.loc[x.date]
        s = _size(x)
        full = float(r.pl_static)
        oracle = max(float(r.pl_e3), float(r.pl_e4), 0.0)
        hist.append(dict(date=x.date, s=s, realized=s * full, full=full,
                         oracle=oracle))
    h = pd.DataFrame(hist)
    y = h.iloc[-1]
    tail = h.tail(window)
    return {
        "date": y.date,
        "your_size": round(y.s, 2),
        "realized_usd": round(y.realized),
        "full_size_counterfactual_usd": round(y.full),
        "oracle_usd": round(y.oracle),
        "sizing_regret_usd": round(y.realized - y.full),
        "read_regret_usd": round(y.realized - y.oracle),
        "rolling_20d": {
            "your_cumulative_sizing_regret_usd": round((tail.realized - tail.full).sum()),
            "your_cumulative_read_regret_usd": round((tail.realized - tail.oracle).sum()),
            "your_arm_expectancy_usd": round(tail.realized.mean()),
            "champion_expectancy_usd": round(tail.full.mean()),
        },
    }


# ------------------------------------------------- v0.6.2: event-family analogs

FAMILIES = {
    "CPI": ("cpi",), "PPI": ("ppi",), "PCE": ("pce",),
    "NFP": ("non-farm", "nonfarm", "payroll", "unemployment rate",
            "average hourly earnings"),
    "ISM": ("ism",), "GDP": ("gdp",), "RETAIL": ("retail sales",),
    "FOMC": ("fomc", "federal funds", "fed chair", "rate decision"),
    "JOBLESS": ("jolts", "employment change"),
}


def _families_of(events: list[str]) -> list[str]:
    out = []
    for fam, keys in FAMILIES.items():
        if any(k in e.lower() for e in events for k in keys):
            out.append(fam)
    return out


def event_analogs(day: str, calendar: pd.DataFrame, books: pd.DataFrame,
                  k: int = 8) -> dict | None:
    """A3: the last k SAME-EVENT-FAMILY mornings before `day`, with what paid.

    calendar: datetime_ET (tz-aware) / event / impact. books: day-indexed
    pl_e3/pl_e4 (use the R1/R2-floored books for v0.6.2 so 'what paid' means
    'what paid under the timing floor the engine actually enforces').
    """
    cal = calendar[calendar.impact == "high"].copy()
    cal["d"] = cal.datetime_ET.dt.strftime("%Y-%m-%d")
    today = cal[cal.d == day]
    if today.empty:
        return None
    fams = _families_of(list(today.event))
    if not fams:
        return None
    keys = tuple(k2 for f in fams for k2 in FAMILIES[f])
    prior = cal[(cal.d < day) & cal.event.str.lower().str.contains("|".join(keys))]
    days = [d for d in sorted(prior.d.unique(), reverse=True) if d in books.index][:k]
    if not days:
        return None
    rows = []
    for d in sorted(days):
        e3, e4 = float(books.loc[d, "pl_e3"]), float(books.loc[d, "pl_e4"])
        act = "FLAT" if max(e3, e4) <= 0 else ("ROTATION" if e3 >= e4 else "MOMENTUM")
        rows.append(dict(day=d, best_action=act, rotation=round(e3), momentum=round(e4)))
    acts = [r["best_action"] for r in rows]
    return dict(families=fams, k=len(rows),
                counts={a: acts.count(a) for a in ("FLAT", "ROTATION", "MOMENTUM")},
                days=rows)


def build_v062_briefing(briefing: dict, day: str, calendar: pd.DataFrame,
                        books: pd.DataFrame, verdict_ledger: pd.DataFrame | None,
                        asof: str | None = None) -> dict:
    """Assemble the full v0.6.2 briefing: priced retrieval (W2) + event-family
    analogs (A3) + the dollar bill (W1, C2 contract as ruled by Angus 19 Jul).

    verdict_ledger: prior graded verdicts of this lineage (day/action/agent_pl
    columns plus stand_down/size via merge upstream) used as the feedback source;
    in a parallel run this is the predecessor version's ledger — disclosed in any
    report. None -> feedback line reads "(no prior verdict yet)".
    """
    briefing = upgrade_briefing(briefing, day, asof=asof)
    ea = event_analogs(day, calendar, books)
    if ea is not None:
        briefing["event_family_analogs"] = ea
    briefing["yesterday_result"] = (
        ledger_feedback(day, verdict_ledger) if verdict_ledger is not None
        else "(no prior verdict yet)")
    return briefing


def ledger_feedback(day: str, ledger: pd.DataFrame, window: int = 20) -> dict | str:
    """C2 bill from a GRADED LEDGER (day/action/agent_pl/oracle_pl [+ size]).

    agent_pl is the agent's chosen book at FULL size; `size` (if present) is the
    verdicted multiplier. realized = size x agent_pl; sizing regret bills the
    shrinkage of the agent's own call, read regret bills the distance to oracle.
    """
    h = ledger[ledger.day < day].sort_values("day")
    if h.empty:
        return "(no prior verdict yet)"
    h = h.copy()
    h["s"] = h["size"] if "size" in h.columns else 1.0
    h["realized"] = h.s * h.agent_pl
    y = h.iloc[-1]
    tail = h.tail(window)
    return {
        "date": y.day, "your_size": round(float(y.s), 2),
        "realized_usd": round(y.realized),
        "full_size_counterfactual_usd": round(y.agent_pl),
        "oracle_usd": round(y.oracle_pl),
        "sizing_regret_usd": round(y.realized - y.agent_pl),
        "read_regret_usd": round(y.realized - y.oracle_pl),
        "rolling_20d": {
            "your_cumulative_sizing_regret_usd": round((tail.realized - tail.agent_pl).sum()),
            "your_cumulative_read_regret_usd": round((tail.realized - tail.oracle_pl).sum()),
            "your_arm_expectancy_usd": round(tail.realized.mean()),
        },
    }
