#!/usr/bin/env python3
"""DOCTRINE REGISTER — every rule in the four contracts, with provenance.

    python -m scripts.doctrine_register            # rewrites docs/DOCTRINE-REGISTER.md

Exists because of T40. A Monday gate sat in tv-thesis 0.4.1-0.4.2 as a
first-person quote he never ratified; its introducing commit cited no
transcript; its veto branch never fired on fit data (the narrated week's
Monday HAD a gap); the first time it blocked anything was the out-of-fit
Monday, at -6.9R. Shown the quote, his ruling (2026-08-18): "i do not
remember saying this at all, and its not true."

So: every version-header entry across the four agent contracts, in one
table, with (a) what it cites for provenance and (b) a rough class. Rules
whose entry cites no dated source are flagged UNSOURCED. He confirms or
kills each — VETO-class first, because a veto's cost is invisible until an
out-of-fit day exercises it.

The generated file is docs/DOCTRINE-REGISTER.md. Regenerate after any
contract change; hand-edits to the generated file are overwritten (record
his verdicts by editing the STATUS overrides below).
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ["tv-macro-events", "tv-thesis", "tv-trigger", "tv-manage"]

# his verdicts land here as they arrive: (contract, version) -> status
STATUS = {
    ("tv-thesis", "0.4.1"): "**STRUCK 0.4.3** — his ruling 2026-08-18",
    ("tv-thesis", "0.4.3"): "his ruling 2026-08-18 (the strike itself)",
    ("tv-thesis", "0.4.4"): "sourced: his narration 2026-08-18, in-chat — the source IS the sign-off",
    ("tv-trigger", "0.4.11"): "sourced: his narration 2026-08-18, in-chat",
    ("tv-trigger", "0.4.12"): "sourced: his ruling 2026-08-18 after pulling the plug on wr1",
    ("tv-manage", "0.3.4"): "paired with T78, same ruling 2026-08-18",
    ("tv-manage", "0.3.3"): "50/50 per his ruling 2026-08-17; trail clause is disambiguation, no new doctrine",
    ("tv-trigger", "0.4.8"): "**FLAGGED**: unsourced, and his narration 2026-08-18 (T77 re-break re-entry) cuts against the cap — awaiting his verdict",
    ("tv-macro-events", "0.2.0"): "**FLAGGED**: T39 FOMC is an unsourced VETO — awaiting his verdict",
}

VETO_PAT = re.compile(r"stand_aside|closed|blackout|may NOT|never |no entries"
                      r"|requires|gate|cut off|forbid|not counter-traded"
                      r"|does not license|only trade", re.I)
SIZE_PAT = re.compile(r"grade|conviction|size|cap[s ]|light|risk", re.I)
SHAPE_PAT = re.compile(r"target|stop|trail|partial|entry|licen[cs]e|fade"
                       r"|flip|re-?entry", re.I)
DATE_PAT = re.compile(r"20\d\d-\d\d-\d\d")
VOICE_PAT = re.compile(r"\bhis \w+|deep interview|he (said|ruled|called)|in-chat", re.I)


def entries(path: Path):
    """(version, text) for each '# <ver>: ...' block in the header comment."""
    out, cur_ver, cur = [], None, []
    for line in path.read_text().splitlines():
        m = re.match(r"#\s+(\d+\.\d+\.?\d*):\s*(.*)", line)
        if m:
            if cur_ver:
                out.append((cur_ver, " ".join(cur)))
            cur_ver, cur = m.group(1), [m.group(2)]
        elif cur_ver is not None:
            if re.match(r"#\s{2,}\S", line):
                cur.append(line.lstrip("# ").strip())
            else:
                break
    if cur_ver:
        out.append((cur_ver, " ".join(cur)))
    return out


def classify(text: str) -> str:
    tags = []
    if VETO_PAT.search(text): tags.append("VETO")
    if SIZE_PAT.search(text): tags.append("SIZE")
    if SHAPE_PAT.search(text): tags.append("SHAPE")
    return "/".join(tags) or "INFO"


def provenance(text: str) -> str:
    dated = DATE_PAT.search(text)
    voiced = VOICE_PAT.search(text)
    if dated and voiced:
        return f"cites him, {dated.group(0)}"
    if voiced:
        return "cites him, NO DATE"
    return "**UNSOURCED**"


def main() -> int:
    lines = [
        "# DOCTRINE REGISTER — every rule, its provenance, his verdict",
        "",
        "**Generated by `scripts/doctrine_register.py` — do not hand-edit; his",
        "verdicts are recorded in the script's STATUS table and regenerated.**",
        "",
        "Why this exists: T40 (`tv-thesis` 0.4.1) sat in the contract as a",
        "first-person quote he never ratified. Its introducing commit cited no",
        "transcript. Its veto branch never fired on fit data — the narrated",
        "week's Monday HAD a gap — so the first time it blocked anything was",
        "the out-of-fit Monday, at −6.9R. Shown the quote, his ruling",
        "(2026-08-18): *\"i do not remember saying this at all, and its not",
        "true.\"* Struck in 0.4.3.",
        "",
        "Two standing conclusions from that:",
        "",
        "1. **A veto rule whose veto branch never fired on fit data is an",
        "   untested rule.** It costs nothing until an out-of-fit day exercises",
        "   it. VETO rows below get his eyes first.",
        "2. **Sign-off protocol, effective now:** no rule enters a contract",
        "   without (a) a verbatim quote or a dated ruling as its source, and",
        "   (b) his explicit confirmation. Version headers must cite the date.",
        "   Quotes are transcript pulls, never reconstructions.",
        "",
        "Verdict key: blank = awaiting his pass · confirmed = he ratified ·",
        "STRUCK = he disavowed, removed from the contract.",
        "",
    ]
    n_unsourced = n_rows = 0
    for name in CONTRACTS:
        p = ROOT / f".claude/agents/{name}.md"
        if not p.exists():
            continue
        vs = re.search(r"^version:\s*(\S+)", p.read_text(), re.M)
        lines += [f"## {name} (now {vs.group(1) if vs else '?'})", "",
                  "| ver | rules | class | provenance | his verdict |",
                  "|-----|-------|-------|------------|-------------|"]
        for ver, text in entries(p):
            ts = ",".join(dict.fromkeys(re.findall(r"T\d+", text))) or "—"
            prov = provenance(text)
            n_rows += 1
            if "UNSOURCED" in prov:
                n_unsourced += 1
            desc = text[:100].rstrip() + ("…" if len(text) > 100 else "")
            desc = desc.replace("|", "\\|")
            status = STATUS.get((name, ver), "")
            lines.append(f"| {ver} | {ts} | {classify(text)} | {prov} | {status} |")
            lines.append(f"| | | | *{desc}* | |")
        lines.append("")
    q = 0
    for name in CONTRACTS:
        p = ROOT / f".claude/agents/{name}.md"
        if p.exists():
            q += len(re.findall(r'>\s*\*"', p.read_text()))
    lines += [
        f"**{n_rows} versioned rule entries; {n_unsourced} carry no source",
        f"citation at all. {q} quoted blocks are presented as his voice across",
        "the four contracts — every one of them is subject to the same",
        "challenge T40 failed.**",
        "",
    ]
    out = ROOT / "docs/DOCTRINE-REGISTER.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} — {n_rows} entries, {n_unsourced} unsourced, {q} quote blocks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
